### PR TITLE
Create Makefile

### PR DESCRIPTION
**Pull request by gio217**
Created a Makefile so installation can be easier

### CODE REVIEW

**Review by emilydaemon — CHANGES_REQUESTED** [review]
There is no need to start the config.sh file, also, ~/.config/candybar isn't in path. Perhaps you could copy to /usr/local/bin?

**Comment by gio217** [comment]
Updated it

**Review by emilydaemon — CHANGES_REQUESTED** [review]
Only candybar.sh has to be in /usr/local/sh, and it should be renamed to just "candybar". Everything else goes in the config directory.

**Comment by at0mdud3** [comment]
oh ok lol

Il giorno mar 26 apr 2022 alle ore 13:16 jornmann ***@***.***>
ha scritto:

**Comment by gio217** [comment]
oh ok lol
it should work now

**Comment by gio217** [comment]
this is my first commit and i hecking love that
thanks ^^

**Pull request merged**
