### PR TITLE
Modified the module_alsa + renamed into module_vol

### PR DESCRIPTION
**Pull request by GabubuAvailable**
While renaming I added the PulseAudio volume perc. I added the solve for this in your reedmeedotemdee :>

### CODE REVIEW

**Comment by emilydaemon** [comment]
Hmm, you should add autodetection for amixer/pamixer

**Comment by GabubuAvailable** [comment]
well need to find a way to do that.
ig i can close this and continue modifying :)

**Comment by emilydaemon** [comment]
You don't have to close this, all future commits are added automatically to the PR

**Comment by GabubuAvailable** [comment]
Now it's done ig

**Comment by GabubuAvailable** [comment]
it uses this command

module_vol() {
	export bar="${bar}${1}$(if command -v pamixer > NULL; then pamixer --get-volume; else amixer sget Master | awk -F'[][]' '/Mono:/ { print $2 }'; fi)${2}"
}

**Comment by GabubuAvailable** [comment]
thanks github for shit alignment

**Review by emilydaemon — APPROVED** [review]
Needs a bit of work, but I'd be happy to do that myself. Merging to a new branch.

**Pull request merged**
